// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/0de1b9fc3d8a2a8fbd39b6493b8db1ad930c4878/js-base64/js-base64.d.ts
interface Base64 {
    /**
     * .encode
     * @param {String} string
     * @return {String}
     */
    encode(base64: string): string;

    /**
     * .encodeURI
     * @param {String} string
     * @return {String}
     */
    encodeURI(base64: string): string

    /**
     * .decode
     * @param {String} string
     * @return {String}
     */
    decode(base64: string): string

    /**
     * Library version
     */
    VERSION:string
}

declare module 'js-base64' {
    const Base64: Base64
}
